In [14]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 


In [44]:
class neuron:
    
    def __init__(self, n_inputs, activation, Lr = 0.01):
        self.w = np.random.randn(n_inputs, 1)
        self.b = np.zeros((1, 1))
        self.lose =[] #for viz
        self.activation = activation
        self.Lr = Lr
        self.n_inputs = n_inputs

    #activation functions
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-np.clip(z, -250, 250)))
    
    def relu(self, z):
        return np.maximum(0, z)
    
    def tanh(self, z):
        return np.tanh(z) 
    
    #forward path to activate the neuron
    def forward(self, X):
        z = X @ self.w + self.b

        #calling activation functions to activate the neuron to produce output(prediction)
        if self.activation == "Linear":
            y_pred = z
        elif self.activation == "Relu":
            y_pred = self.relu(z)
        elif self.activation == "Tanh":
            y_pred = self.tanh(z)
        elif self.activation == "Sigmoid":
            y_pred = self.sigmoid(z)

        #local_deriative
        self.dw = X
        self.db = 1
        self.dx = self.w.T

        return y_pred

    # backword --> calculate gradients
    def backword(self, y_pred, Y_true):
        #loss function first
        if self.activation == "Linear":
            L = np.mean((Y_true - y_pred) ** 2)
        elif self.activation == "Relu":
            L = - [(1 / self.n_inputs) * np.mean(Y_true * np.log(y_pred) + (1 - Y_true) * np.log(1 - y_pred))]
        #elif self.activation == "Tanh":
        #    self.L = 
        
        #filling the loss list for viz
        self.lose.append(L)
        
        # global deriviatives
        if self.activation == "Linear":
            L = np.mean((Y_true - y_pred) ** 2)
            dy_dz = 1
            dL_dy = 2 * (Y_true - y_pred) * dy_dz
        elif self.activation == "Relu":
            if y_pred == 0 :
                dy_dz = 0 
            else:
                dy_dz = 1
            dL_dy = (-(Y_true / y_pred + (1- Y_true)/(1-y_pred))) * dy_dz  # this is temporar till I find the correct answer
        #elif self.activation == "Tanh":
        #    self.dy_dz = 
        #    self.dL_dy = 
        
        #update parameters
        self.w = self.w - self.Lr * dy_dz
        self.b = self.b - self.Lr * dy_dz

        print("w = ", self.w)
        print("b = ", self.b)
        print(self.lose)





In [ ]:
X_sample = np.array([[0.5, -1.2, 0.8]])
#Y = 1
#n = neuron(3, activation='Linear')
#y_pred = n.forward(X_sample)
#back = n.backword(y_pred, Y)


w =  [[ 0.86247632]
 [-1.44910616]
 [-1.65350545]]
b =  [[-0.01]]
Loss value =  [np.float64(0.02299433027930645)]


In [48]:
class DesnsLayer:

    #n_output mean the number of neurons per layer
    def __init__(self, n_inputs, n_outputs, activation, Lr = 0.01):
        self.w = np.random.randn(n_inputs, n_outputs) * 0.1 # here we multiplied by 0.1 to avoid the explding of the gradients because if the values of w came large then z will be big
        self.b = np.zeros((1, n_outputs))
        self.activation = activation
        self.Lr = Lr
        self.lose =[] #for viz
        self.n_inputs = n_inputs
        self.n_outputs = n_outputs

    #activation functions
    def sigmoid(self, X):
        return 1 / (1 + np.exp(-np.clip(X, -250, 250)))
    
    def relu(self, X):
        return np.maximum(0, X)
    
    def tanh(self, X):
        return np.tanh(X)

    def forward(self, X):
        z = X @ self.w + self.b
        #print(z)

        #calling activation functions to activate the neuron to produce output(prediction)
        if self.activation == "Linear":
            y_pred = z
        elif self.activation == "Relu":
            y_pred = self.relu(z)
        elif self.activation == "Tanh":
            y_pred = self.tanh(z)
        elif self.activation == "Sigmoid":
            y_pred = self.sigmoid(z)

        #local_deriative
        self.dw = X
        self.db = 1
        self.dx = self.w.T

        return y_pred

    # backword --> calculate gradients
    def backword(self, y_pred, Y_true):
        #loss function first
        if self.activation == "Linear":
            L = np.mean((Y_true - y_pred) ** 2)
        elif self.activation == "Relu":
            L = - [(1 / self.n_inputs) * np.mean(Y_true * np.log(y_pred) + (1 - Y_true) * np.log(1 - y_pred))]
        #elif self.activation == "Tanh":
        #    self.L = 
        
        self.lose.append(L)
        
        # global deriviatives
        if self.activation == "Linear":
            L = np.mean((Y_true - y_pred) ** 2)
            dy_dz = 1
            dL_dy = 2 * (Y_true - y_pred) * dy_dz
        elif self.activation == "Relu":
            if y_pred == 0 :
                dy_dz = 0 
            else:
                dy_dz = 1
            dL_dy = (-(Y_true / y_pred + (1- Y_true)/(1-y_pred))) * dy_dz  # this is temporar till I find the correct answer
        #elif self.activation == "Tanh":
        #    self.dy_dz = 
        #    self.dL_dy = 
        
        #update parameters
        self.w = self.w - self.Lr * dy_dz
        self.b = self.b - self.Lr * dy_dz

        print("w = ", self.w)
        print("b = ", self.b)
        print("Loss value = ", self.lose)
        print("Note :if you want to see layer architechture call the function (viz)")

    def viz(self):
        plt.figure(figsize=(10, 6))
        plt.title("🧠 Neural Layer Architecture", fontsize=14, pad=20)

        # Draw neurons
        for i in range(self.n_inputs):  # Input layer
            plt.scatter(0, i, s=500, c='lightblue', edgecolors='black', zorder=5)
            plt.text(0, i, f'x{i+1}', ha='center', va='center', fontweight='bold')
            
        for j in range(self.n_outputs):  # Output layer
            plt.scatter(2, j, s=500, c='lightgreen', edgecolors='black', zorder=5)
            plt.text(2, j, f'a{j+1}', ha='center', va='center', fontweight='bold')
            
            # Draw connections
            for i in range(self.n_inputs):
                plt.plot([0, 2], [i, j], 'gray', alpha=0.3)

        plt.xlim(-0.5, 2.5)
        plt.ylim(-0.5, 4.5)
        plt.axis('off')
        plt.text(0, -0.3, f"Input Layer {self.n_inputs}, neurons", ha='center', fontsize=12)
        plt.text(2, -0.3, f"Dense Layer {self.n_outputs}, neurons", ha='center', fontsize=12)
        plt.show()



In [ ]:
X_sample = np.array([[0.5, -1.2, 0.8]])
#Y = 1
n = DesnsLayer(3, 4, activation='Linear')
#y_pred = n.forward(X_sample)
print(y_pred)
back = n.backword(y_pred, Y)
v = n.viz()


In [ ]:
#model building stack of layers


In [ ]:
#Breast Cancer Dataset
from sklearn.datasets import load_breast_cancer
import pandas as pd

def data_loading(Dataset):
    #exploring the data
    bcd = load_breast_cancer()
    #print(bcd.keys())

    X = pd.DataFrame(data = bcd.data)
    #X = bcd.data
    print(X.shape[1])
    Y = pd.DataFrame(data = bcd.target)
    #print(Y)
    #print(X.info)
    return X, Y

def train_test_split(Dataset):


30


In [ ]:
#trying to call the neuron class
X, Y_true = data_loading()
print(X)
n = neuron(X.shape[1], activation='Linear')
y_pred = n.forward(X)
back = n.backword(y_pred, Y_true)

In [ ]:
#trying dense layer class  DesnsLayer

#X_sample = np.array([[0.5, -1.2, 0.8]])
#Y = 1
n = DesnsLayer(X.shape[1], 4, activation='Linear')
y_pred = n.forward(X)
print(y_pred)
back = n.backword(y_pred, Y)
v = n.viz()


              0           1           2           3
0   -319.549072  321.133608 -263.750678 -161.207315
1   -305.500220  286.879528 -268.443461 -180.950544
2   -271.221174  256.564580 -242.135548 -164.561453
3    -93.828847   90.149491  -82.322888  -53.501102
4   -256.437776  233.122119 -239.812816 -169.101494
..          ...         ...         ...         ...
564 -324.080460  309.997023 -294.507778 -203.426967
565 -273.163303  260.040351 -246.124725 -170.493688
566 -179.264762  167.862240 -162.752944 -113.023283
567 -287.289567  272.962961 -254.988001 -172.170589
568  -43.632245   46.310725  -37.854894  -25.646197

[569 rows x 4 columns]
w =  [[-2.62108341e-01 -4.71825521e-02  1.45134004e-01 -1.85414145e-01]
 [ 5.52044993e-02 -5.37224363e-03  4.45424229e-02  2.80827767e-02]
 [-1.04544749e-01  6.04698679e-02 -1.35176557e-01 -3.06359526e-02]
 [-1.84753503e-02 -4.05249159e-02 -7.47747412e-02 -9.52241447e-02]
 [-1.75625044e-01  2.27079424e-01  1.59745493e-01  1.55367065e-01]
 [-3.1594320

In [ ]:
#model evaluation